version: '3.9'

services:

  rec_viz_airflow_db:
    image: rec_viz_airflow_db
    build:
      context: airflow/db
    container_name: rec_viz_airflow_db
    restart: always
    ports:
      - 5932:5432
    volumes:
      - airflow_data:/var/lib/postgresql/data

  rec_viz_db:
    image: rec_viz_db
    build:
      context: server/db
    container_name: rec_viz_db
    restart: always
    ports:
      - 5933:5432
    volumes:
      - rec_viz_db:/var/lib/postgresql/data

  job_queue:
    image: redis:6.0-alpine
    container_name: job_queue
    depends_on:
      - rec_viz_db
      - rec_viz_airflow_db
    ports:
      - 6380:6379
    volumes: 
      - job_queue:/data

  rec_viz_server:
    image: rec_viz_server
    build:
      context: server
    container_name: rec_viz_server
    restart: always
    depends_on:
      - job_queue
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=job_queue
      - REDIS_PORT=6379
    volumes:
      - ./common:/workspaces/server/common:rw
      - ./applications:/workspaces/server/applications:rw

  airflow_server:
    image: airflow_server
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: airflow_server
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker-proxy:2375
    depends_on:
      - rec_viz_airflow_db
    ports:
      - 8080:8080
    volumes:
      - ./common:/workspaces/airflow/common:rw
      - ./applications:/workspaces/airflow/applications:rw
      - /tmp/airflow_recviz:/tmp/airflow_recviz:rw

  # docker-socket-proxy:
  #   image: tecnativa/docker-socket-proxy:0.1.1
  #   environment:
  #     CONTAINERS: 1
  #     IMAGES: 1
  #     AUTH: 1
  #     POST: 1
  #   privileged: true
  #   volumes:
  #     - /var/run/docker.sock::/var/run/docker.sock
  #   restart: always
  docker-proxy:
    image: bobrik/socat
    command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
    ports:
      - "2376:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  


volumes:
  airflow_data: 
  rec_viz_db:
  job_queue:
