# Generated by Django 4.1.5 on 2023-02-09 21:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='python', max_length=256)),
                ('source', models.TextField()),
                ('func_name', models.CharField(max_length=256)),
                ('source_checksum', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.IntegerField(choices=[(10, 'Queued'), (20, 'Running'), (30, 'Complete'), (500, 'Error')], default=10)),
                ('source_file', models.CharField(max_length=256)),
                ('error', models.TextField(null=True)),
                ('result', models.JSONField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.code')),
            ],
        ),
    ]
