# Generated by Django 4.1.6 on 2023-02-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='source_file',
            new_name='source_filename',
        ),
    ]
